apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMq__User: fcg
  Jwt__Issuer: fcg-users-api
  Jwt__Audience: fcg-client
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=catalog-db,1433;Database=catalogdb;User Id=sa;Password=Fcg@12345;TrustServerCertificate=True
  RabbitMq__Password: fcg123
  Jwt__Key: change-this-local-development-key-with-many-characters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: fcg-catalog-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: fcg
spec:
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 8080
